### ISSUE TITLE
Kwargs with `_` don't work

### ISSUE THREAD

**Issue by yonromai** [haydenflinner/magicinvoke#2]
Hi @haydenflinner,

This looks like a bug:

When running:
```
inv mytask --foo-bar baz
```
I get: `kwargs={'foo-bar': 'baz'}`

But when running:
```
inv mytask --foo_bar baz
```
I get: 
```
Traceback (most recent call last):
  File "./venv/bin/inv", line 10, in <module>
    sys.exit(program.run())
  File "./venv/lib/python3.6/site-packages/invoke/program.py", line 397, in run
    self.parse_tasks()
  File "./venv/lib/python3.6/site-packages/invoke/program.py", line 741, in parse_tasks
    result = self.parser.parse_argv(self.core.unparsed)
  File "./venv/lib/python3.6/site-packages/invoke/parser/parser.py", line 169, in parse_argv
    machine.handle(token)
  File "./venv/lib/python3.6/site-packages/invoke/parser/parser.py", line 253, in handle
    self.switch_to_flag(token)
  File "./venv/lib/python3.6/site-packages/invoke/parser/parser.py", line 429, in switch_to_flag
    self.flag = self.context.flags[flag]
  File "./venv/lib/python3.6/site-packages/invoke/vendor/lexicon/alias_dict.py", line 80, in __getitem__
    return self._handle(key, None, single, multi, unaliased)
  File "./venv/lib/python3.6/site-packages/invoke/vendor/lexicon/alias_dict.py", line 62, in _handle
    return unaliased(self, key, value)
  File "./venv/lib/python3.6/site-packages/invoke/vendor/lexicon/alias_dict.py", line 74, in unaliased
    def unaliased(d, key, value): return super(AliasDict, d).__getitem__(key)
KeyError: '--foo_bar'
```

**Comment by haydenflinner** [comment]
/magicinvoke/invoke/tasks.py:312

It seems that it's on the user of the Argument class to call its constructor correctly with the 'attr_name'. Even after doing that, for some reason the 'Lexicon' thing still gave us the KeyError. So the quick hack of translating underscores before asking the Lexicon worked. Also gave me an idea to fix --pasing_args_like this. Thanks for the report!

**Comment by haydenflinner** [comment]
Forgot to push to pip, pushed it in 2.4.5 along with some other stuff today. Enjoy!
